import {
  getLocalizedOutOfScopeReply,
  normalizeForLanguageDetection,
} from "@/lib/ai/engine/language";

export type GuestScopeDecision = {
  allowed: boolean;
  reason: string;
  reply?: string;
};

function includesAny(message: string, words: string[]) {
  return words.some((word) => message.includes(word.toLowerCase()));
}

export function evaluateGuestQuestionScope(message: string): GuestScopeDecision {
  const normalized = normalizeForLanguageDetection(message);

  if (!normalized) {
    return {
      allowed: false,
      reason: "empty_message",
      reply: getLocalizedOutOfScopeReply(message),
    };
  }

  if (normalized.length > 900) {
    return {
      allowed: false,
      reason: "message_too_long",
      reply: getLocalizedOutOfScopeReply(message),
    };
  }

  const disallowedPatterns = [
    "write my cv",
    "write a cv",
    "resume",
    "cover letter",
    "job application",
    "curriculum",
    "lettera di presentazione",
    "candidatura",
    "write code",
    "python",
    "javascript",
    "typescript",
    "sql query",
    "debug my code",
    "homework",
    "essay",
    "assignment",
    "crypto investment",
    "stock advice",
    "trading advice",
    "legal advice",
    "tax advice",
    "medical advice",
    "diagnose",
    "prescription",
    "political",
    "election",
    "porn",
    "adult content",
    "weapon",
    "explosive",
    "bomb",
    "hack",
    "malware",
    "phishing",
    "steal",
    "fake id",
    "bypass security",
  ];

  if (includesAny(normalized, disallowedPatterns)) {
    return {
      allowed: false,
      reason: "clearly_out_of_scope_or_unsafe",
      reply: getLocalizedOutOfScopeReply(message),
    };
  }

  const allowedStayPatterns = [
    "wifi",
    "wi fi",
    "wi-fi",
    "wlan",
    "internet",
    "password",
    "network",
    "check in",
    "check-in",
    "checkout",
    "check out",
    "arrival",
    "departure",
    "arrive",
    "leave",
    "access",
    "door",
    "key",
    "keys",
    "lockbox",
    "code",
    "apartment",
    "property",
    "house",
    "villa",
    "flat",
    "stay",
    "booking",
    "reservation",
    "address",
    "location",
    "directions",
    "parking",
    "park",
    "car",
    "garage",
    "allowed",
    "allow",
    "can i",
    "may i",
    "is it ok",
    "is it okay",
    "rules",
    "house rules",
    "quiet",
    "smoking",
    "smoke",
    "party",
    "parties",
    "event",
    "events",
    "pets",
    "pet",
    "guests",
    "maximum guests",
    "max guests",
    "occupancy",
    "trash",
    "rubbish",
    "garbage",
    "recycling",
    "ac",
    "air conditioning",
    "heating",
    "boiler",
    "hot water",
    "shower",
    "washing machine",
    "washer",
    "kitchen",
    "oven",
    "fridge",
    "appliance",
    "hairdryer",
    "hair dryer",
    "dryer",
    "iron",
    "ironing",
    "towels",
    "linen",
    "bed",
    "sofa",
    "tv",
    "remote",
    "pool",
    "amenity",
    "amenities",
    "restaurant",
    "restaurants",
    "food",
    "eat",
    "bar",
    "coffee",
    "breakfast",
    "supermarket",
    "shop",
    "pharmacy",
    "beach",
    "local",
    "nearby",
    "things to do",
    "transport",
    "bus",
    "taxi",
    "bolt",
    "uber",
    "ferry",
    "airport",
    "emergency",
    "urgent",
    "police",
    "hospital",
    "doctor",
    "host",
    "contact",
    "help",
    "problem",
    "issue",
    "broken",
    "not working",
    "cockroach",
    "insect",
    "insects",
    "bug",
    "bugs",
    "mosquito",
    "mosquitoes",
    "mold",
    "mould",
    "leak",
    "water",
    "electricity",
    "power",
    "noise",
    "construction",
    "housekeeping",
    "ciao",
    "grazie",
    "dove",
    "come",
    "quando",
    "posso",
    "appartamento",
    "parcheggio",
    "ristorante",
    "ristoranti",
    "spazzatura",
    "regole",
    "chiavi",
    "porta",
    "doccia",
    "acqua calda",
    "lavatrice",
    "bonjour",
    "merci",
    "où",
    "comment",
    "quand",
    "appartement",
    "règles",
    "départ",
    "arrivée",
    "clés",
    "douche",
    "hola",
    "gracias",
    "dónde",
    "cómo",
    "cuándo",
    "contraseña",
    "aparcamiento",
    "apartamento",
    "reglas",
    "salida",
    "llegada",
    "llaves",
    "hallo",
    "danke",
    "wo",
    "wie",
    "wann",
    "passwort",
    "parken",
    "wohnung",
    "regeln",
    "schlüssel",
  ];

  if (includesAny(normalized, allowedStayPatterns)) {
    return {
      allowed: true,
      reason: "stay_related",
    };
  }

  const shortGreetingPatterns = [
    "hi",
    "hello",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "thanks",
    "thank you",
    "ciao",
    "buongiorno",
    "buonasera",
    "grazie",
    "bonjour",
    "bonsoir",
    "merci",
    "hola",
    "buenos dias",
    "buenas tardes",
    "gracias",
    "hallo",
    "guten morgen",
    "guten abend",
    "danke",
  ];

  if (normalized.length <= 80 && includesAny(normalized, shortGreetingPatterns)) {
    return {
      allowed: true,
      reason: "guest_greeting",
    };
  }

  return {
    allowed: false,
    reason: "not_related_to_guest_stay",
    reply: getLocalizedOutOfScopeReply(message),
  };
}